name: Auto2
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/30 * * * *'
  workflow_dispatch:

env:
  CONFIG: ${{ secrets.CONFIG }}
  SETUP_CMD: ${{ secrets.SETUP_CMD }}
  RUN_CMD: ${{ secrets.RUN_CMD2 }}
  FIN_CMD: ${{ secrets.FIN_CMD }}

jobs:
  Build:
    runs-on: ubuntu-slim
    steps:
      - name: Setup
        run: |
          pwsh -EncodedCommand $SETUP_CMD

      - name: Run
        continue-on-error: true
        run: |
          pwsh -EncodedCommand $RUN_CMD

      - name: Finish
        run: |
          pwsh -EncodedCommand $FIN_CMD
